# Generated by Django 5.2.6 on 2025-10-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('password', models.CharField(blank=True, help_text='Optional password to protect the form', max_length=100)),
                ('require_captcha', models.BooleanField(default=True, help_text='Require captcha for submissions')),
                ('form_settings', models.JSONField(default=dict)),
                ('form_image', models.ImageField(blank=True, help_text='Header image for the form', null=True, upload_to='form_images/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form', 'user')},
            },
        ),
        migrations.AddField(
            model_name='form',
            name='editors',
            field=models.ManyToManyField(related_name='collaborative_forms', through='forms.FormCollaboration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description can include URLs and HTML')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section header', null=True, upload_to='section_images/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms.form')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('text_input', 'Text Input'), ('numeric_input', 'Numeric Input'), ('date_input', 'Date Input'), ('image_prompt', 'Image Prompt'), ('image_select', 'Image Select (choose from image options)')], max_length=20)),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('logic', models.JSONField(default=dict)),
                ('image', models.ImageField(blank=True, help_text='Image to display with the question', null=True, upload_to='question_images/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form')),
                ('section', models.ForeignKey(blank=True, help_text='Optional section to group this question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formsection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormMasterDataAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden_columns', models.JSONField(blank=True, default=list)),
                ('display_column', models.CharField(blank=True, help_text='Column to use for displaying records in dropdowns', max_length=100, null=True)),
                ('filter_columns', models.JSONField(blank=True, default=list, help_text="Columns to use as cascading filters (e.g., ['Wilayah', 'Lingkungan'])")),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.masterdataset')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_data_attachments', to='forms.form')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for this option', null=True, upload_to='option_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_images', to='forms.formquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'value')},
            },
        ),
    ]
