# Generated by Django 5.1.1 on 2025-09-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_image',
            field=models.ImageField(blank=True, help_text='Header image for the form', null=True, upload_to='form_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to protect the form', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='require_captcha',
            field=models.BooleanField(default=True, help_text='Require captcha for submissions'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to display with the question', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('text_input', 'Text Input'), ('numeric_input', 'Numeric Input'), ('date_input', 'Date Input'), ('image_prompt', 'Image Prompt'), ('image_select', 'Image Select (choose from image options)')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for this option', null=True, upload_to='option_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_images', to='forms.formquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'value')},
            },
        ),
    ]
