# Generated by Django 5.2.6 on 2025-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_form_image_form_password_form_require_captcha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmasterdataattachment',
            name='hidden_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
