# Generated by Django 5.2.6 on 2025-10-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formmasterdataattachment_hidden_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmasterdataattachment',
            name='display_column',
            field=models.CharField(blank=True, help_text='Column to use for displaying records in dropdowns', max_length=100, null=True),
        ),
    ]
