# Generated by Django 5.2.6 on 2025-10-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_add_display_column_to_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmasterdataattachment',
            name='filter_columns',
            field=models.JSONField(blank=True, default=list, help_text="Columns to use as cascading filters (e.g., ['Wilayah', 'Lingkungan'])"),
        ),
    ]
