# Generated by Django 5.2.6 on 2025-10-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_add_filter_columns_to_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description can include URLs and HTML')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section header', null=True, upload_to='section_images/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms.form')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'order')},
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional section to group this question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formsection'),
        ),
    ]
