# Generated by Django 5.2.6 on 2025-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_add_new_identity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_new_identity',
            field=models.BooleanField(default=False, help_text='True if this response includes new identity data not in master data'),
        ),
        migrations.AddField(
            model_name='response',
            name='new_identity_data',
            field=models.JSONField(blank=True, help_text="New identity information when 'Other' is selected (not yet added to master data)", null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='new_identity_dataset_id',
            field=models.IntegerField(blank=True, help_text='ID of the dataset this new identity belongs to', null=True),
        ),
    ]
